#!/bin/sh
##An example for serial job.
##DO NOT RUN THIS SCRIPT DIRECTLY,
##PLEASE RUN THIS SCRIPT WITH qsub: qsub serial_job.pbs
##
#PBS -N fastp
#PBS -o fastp.log
#PBS -e fastp.err
#PBS -q batch
#PBS -l walltime=300:00:00
#PBS -l nodes=1:ppn=4
##
cd /path_to_data/
source activate
conda deactivate

conda activate Fastq

for file in "sample names"
do
echo $file
fastp \
-i  /path_to_data/upload/${file}_1.fq.gz \
-I  /path_to_data/upload/${file}_2.fq.gz \
-o  /path_to_data/fastp/${file}_clean_1.fq.gz \
-O  /path_to_data/fastp/${file}_clean_2.fq.gz \
-h /path_to_data/fastp/${file}_.html \
-j /path_to_data/fastp/${file}_.json
done
