#!/bin/sh
#an example for Intel MPI job.
#DO NOT RUN THIS SCRIPT DIRECTLY,
#PLEASE RUN THIS SCRIPT WITH qsub: qsub intelmpi_job.pbs
#
#PBS -N featureCounts
#PBS -o featureCounts.log
#PBS -e featureCounts.err
#PBS -q batch
#PBS -l nodes=1:ppn=1
#PBS -l walltime=148:00:00

source activate
conda deactivate
conda activate Rseurat_new

cd /way_to_output/bam/
featureCounts \
-t exon \
-g gene_id \
-a /path_to_reference/reference/Danio_rerio.GRCz11.110.gtf \
-o /path_to_output/bam/counts.txt \
-p \
".bam file names"
