#!/bin/sh
#an example for Intel MPI job.
#DO NOT RUN THIS SCRIPT DIRECTLY,
#PLEASE RUN THIS SCRIPT WITH qsub: qsub intelmpi_job.pbs
#
#PBS -N mapping_STAR
#PBS -o mapping.log
#PBS -e mapping.err
#PBS -q fat
#PBS -l nodes=1:ppn=10
#PBS -l walltime=148:00:00

module load STAR


for file in "sample names"

do
echo $file
STAR \
--runThreadN 10 \
--genomeDir /path_to_reference/reference \
--readFilesCommand gunzip -c \
--outFileNamePrefix /path_to_data/bam/${file}_clean.bam \
--outSAMtype BAM SortedByCoordinate \
--quantMode GeneCounts \
--readFilesIn /path_to_data/fastp/${file}_clean_1.fq.gz /path_to_data/fastp/${file}_clean_2.fq.gz
done


